leauge/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tournament.urls', namespace='tournament')),
]

tournament/urls.py
# tournament\urls.py
from django.urls import path
from . import views
from .views import PlayersCreateView, PlayersStats


app_name = "tournament"

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login, name="login"),
    path("create_tournament/", views.create_tournament, name="create_tournament"),
    path("add_results/", views.add_results, name="add_results"),
    path("add_players/", PlayersCreateView.as_view(), name="create_player_form"),
    path("add_teams/", views.add_teams, name="add_teams"),
    path("add_add_match_results/", views.add_match_results, name="add_match_results"),
    path("view_results/", views.view_results, name="view_results"),
    path("players_statistics/", PlayersStats.as_view(), name="player_statistics"),
    path("team_statistics/", views.team_statistics, name="team_statistics"),
    path("about_site/", views.about, name="about_site"),
    path("some_player/<int:player_id>", views.show_player, name="show_player"),
]

tournament/models.py
from django.db import models
from django.urls import reverse


class Player(models.Model):
    name = models.CharField(max_length=100)
    surname = models.CharField(max_length=100)
    date_of_birth = models.DateField()
    is_active = models.BooleanField(default=True)

    def __str__(self) -> str:
        return f"{self.name} {self.surname}"

    def get_absolute_url(self):
        return reverse("tournament:show_player", kwargs={"player_id": self.pk})


class Team(models.Model):
    name = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    is_active = models.BooleanField(default=True)
    players = models.ManyToManyField(Player, blank=True)

    def __str__(self) -> str:
        return f"{self.name} ({self.city})"


class Tournament(models.Model):
    TOURNAMENT_TYPE_CHOICES = [
        ("cup", "Кубок"),
        ("championship", "Чемпіонат"),
    ]

    name = models.CharField(max_length=100)
    tournament_type = models.CharField(max_length=50, choices=TOURNAMENT_TYPE_CHOICES)
    teams = models.ManyToManyField(Team)
    is_active = models.BooleanField(default=True)

    def __str__(self) -> str:
        return f"{self.name} {self.tournament_type}"


class Match(models.Model):
    tournament = models.ForeignKey(Tournament, on_delete=models.CASCADE)
    team1 = models.ForeignKey(Team, on_delete=models.CASCADE, related_name="team1")
    team2 = models.ForeignKey(Team, on_delete=models.CASCADE, related_name="team2")
    result_team1 = models.IntegerField(default=0)
    result_team2 = models.IntegerField(default=0)

    def __str__(self) -> str:
        return f"{self.team1} {self.result_team1} - {self.result_team2} {self.team2}"


class PlayerEvent(models.Model):
    EVENT_TYPE_CHOICES = [
        ("goal", "Гол"),
        ("penalty_goal", "Гол з пенальті"),
        ("assist", "Передача"),
        ("yellow_card", "Жовта картка"),
        ("red_card", "Червона картка"),
        ("autogoal", "Автогол"),
    ]

    player = models.ForeignKey(Player, on_delete=models.CASCADE)
    match = models.ForeignKey(Match, on_delete=models.CASCADE)
    event_type = models.CharField(max_length=50, choices=EVENT_TYPE_CHOICES)
    minute = models.IntegerField()

    def __str__(self) -> str:
        return f"{self.player} ({self.match}) {self.event_type} ({self.minute})"


class PlayerStats(models.Model):
    player = models.ForeignKey(Player, on_delete=models.CASCADE)
    match = models.ForeignKey(Match, on_delete=models.CASCADE)
    total_minutes_played = models.IntegerField(default=90)

    def __str__(self) -> str:
        return f"{self.player} ({self.match})"

tournament/views.py
# tournament\vews.py
from os import name
from typing import Any
from django.http import HttpResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic
from tournament.models import Player, Team, Match, Tournament, PlayerEvent, PlayerStats
from django.views.generic import ListView


def login(request):
    return render(request, "tournament/login.html")


def index(request):
    return render(request, "tournament/index.html")


def create_tournament(request):
    return render(request, "tournament/create_tournament.html")


def add_results(request):
    return render(request, "tournament/add_results.html")


def view_results(request):
    num_match = Match.objects.count()
    tournaments = Tournament.objects.all()
    Tour_match_list = []

    for tournament in tournaments:
        matches = Match.objects.filter(tournament=tournament)
        matches_list = [match for match in matches]
        tour_match = {
            "tournament_name": tournament.name,
            "matches_list": matches_list,
        }
        Tour_match_list.append(tour_match)

    context = {
        "title": "Результати матчів",
        "num_match": num_match,
        "tour_match_list": Tour_match_list,
        "match_list": matches_list,
    }
    return render(request, "tournament/view_result.html", context=context)


class PlayersStats(ListView):
    model = Player
    template_name = "tournament/player_statistics.html"
    ordering = "-date_of_birth"
    context_object_name = "players"

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Статистика гравців"
        return context

    # метод для визначення даних які передаються в context_object_name
    def get_queryset(self):
        return Player.objects.filter(is_active=True)


class PlayersCreateView(generic.CreateView):
    model = Player
    fields = [
        "name",
        "surname",
        "date_of_birth",
        "is_active",
    ]
    success_url = reverse_lazy("tournament:player_statistics")
    template_name = "tournament/create_player_form.html"


def add_teams(request):
    pass


def add_match_results(request):
    pass


def show_player(request, player_id):
    return HttpResponse(f"Статистика гравця з id={player_id}")


def team_statistics(request):
    num_teams = Team.objects.count()
    teams = Team.objects.all()
    Team_players_list = []

    for team in teams:
        players = Player.objects.filter(team=team)
        players_list = [player for player in players]
        team_context = {
            "team_name": team.name,
            "players_list": players_list,
        }
        Team_players_list.append(team_context)

    context = {
        "title": "Статистика команд",
        "num_teams": num_teams,
        "team_players_list": Team_players_list,
    }
    return render(request, "tournament/team_statistics.html", context=context)


def about(request):
    return render(request, "tournament/about.html")

tournament/templates/tournament/about.html
{% extends 'tournament/base.html' %}

{% block content %}
<h1>{{title}}</h1>
<p>Вміст сторінки про сайт</p>
{% endblock %}

tournament/templates/tournament/add_results.html
{% extends 'tournament/base.html' %}

{% block content %}
<h1>{{title}}</h1>
<p>Вміст сторінки Додати результати</p>
{% endblock %}

tournament/templates/tournament/base.html
{% comment %} tournament\template\tournament\base.html {% endcomment %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{title}}</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'tournament/css/style.css' %}">
</head>
<body class="bg-image">
    <div class="header">
        {% block mainmenu %}
            <ul class="menu">
                <li class="menu-item">
                    <a href="{% url 'tournament:login' %}">Увійти</a>
                </li>
                <li class="menu-item">
                    <a href="{% url 'tournament:index' %}">Головна</a>
                </li>
                <li class="menu-item">
                    <a href="{% url 'tournament:create_tournament' %}">Створити турнір</a>
                    <ul class="submenu">
                        <li class="submenu-item"><a href="#">Кубковий турнір</a></li>
                        <li class="submenu-item"><a href="#">Ліга</a></li>
                        <li class="submenu-item"><a href="#">Товариський матч</a></li>
                      </ul>
                </li>
                <li>
                <li class="menu-item">
                    <a href="#">Внести</a>
                    <ul class="submenu">
                        <li class="submenu-item"><a href="{% url 'tournament:create_player_form' %}">Внести гравців</a></li>
                        <li class="submenu-item"><a href="{% url 'tournament:add_teams' %}">Внести команди</a></li>
                        <li class="submenu-item"><a href="{% url 'tournament:add_match_results' %}">Внести результати матчів</a></li>
                    </ul>
                </li>
                <li class="menu-item">
                    <a href="{% url 'tournament:view_results' %}">Статистика</a>
                    <ul class="submenu">
                        <li class="submenu-item"><a href="{% url 'tournament:team_statistics' %}">Статистика команд</a></li>
                        <li class="submenu-item"><a href="{% url 'tournament:player_statistics' %}">Статистика гравців</a></li>
                        <li class="submenu-item"><a href="#">Статистика по видах спорту</a></li>
                    </ul>
                </li>


            </ul>
        {% endblock mainmenu %}
    </div>

{% block content %}
{% endblock %}
</body>
</html>

tournament/templates/tournament/create_player_form.html
{% extends 'tournament/base.html' %}

{% block content %}
  <h1>Додаємо гравця в базу</h1>

  <form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Записати">
  </form>
{% endblock %}

tournament/templates/tournament/create_tournament.html
{% extends 'tournament/base.html' %}

{% block content %}
<h1>{{title}}</h1>
<p>Вміст сторінки Створити турнір</p>
{% endblock %}

tournament/templates/tournament/index.html
{% extends 'tournament/base.html' %}

{% block content %}
<h1>{{title}}</h1>
<p>Вміст головної сторінки</p>
{% endblock %}

tournament/templates/tournament/login.html
{% extends 'tournament/base.html' %}

{% block content %}
<h1>{{title}}</h1>
<p>Вміст сторінки Авторизація</p>
{% endblock %}

tournament/templates/tournament/player_statistics.html
{% extends 'tournament/base.html' %}

{% block content %}
  <h1>{{ title }}</h1>
  <div class="container">
    <h4>Кількість гравців в базі: {{ players.count }}</h4>
    <ul>
      {% for player in players %}
        <li>
          <p ><a href="{{ player.get_absolute_url }}" class="link-show-player"><b>{{ player }}</b></a></p>
          <ul>
              Команди:
            {% for team in player.team_set.all %}
              <li><i>{{ team }}</i></li>
              {% empty %}
                <li class="empty">У гравця немає команди</li>
            {% endfor %}
          </ul>
        </li>
      {% endfor %}
    </ul>
  </div>
{% endblock %}

tournament/templates/tournament/team_statistics.html
{% extends 'tournament/base.html' %}

{% block content %}
<h1>{{title}}</h1>
<div class="container">
    <p>Кількість команд в базі: {{ num_teams }}</p>
    <p>Список команд в базі:</p>
    {% for team_data in team_players_list %}
        <h4 class="h4">{{ team_data.team_name }}</h4>
        <ul>
            {% for player in team_data.players_list %}
                <li>{{ player }}</li>
            {% endfor %}
        </ul>
    {% endfor %}
</div>
{% endblock %}

tournament/templates/tournament/view_result.html
{% extends 'tournament/base.html' %}

{% block content %}
<h1>{{title}}</h1>
<div class="container">
    <p>Кількість матчів в базі: {{ num_match }}</p>
    {% for tour_match in tour_match_list %}
    <h4 class="h4">{{ tour_match.tournament_name }}</h4>
        {% for res in tour_match.matches_list %}
        <ul>
            <li>
                {{ res }}
            </li>
        </ul>
        {% endfor %}
    {% endfor %}
</div>
{% endblock %}